### ISSUE TITLE
Troll token search doesn't filter records

### ISSUE THREAD

**Issue by ajohn25** [politics-rewired/Spoke#1219]
**Your issue may already be reported!**
Please search on the [issue tracker](../) before creating one.

- [x] I have searched through existing issues and did not find an existing report

**Describe the bug**
Typing in a token to search for on the troll alarms page doesn't filter records as expected.

**To Reproduce**

1.  Go to the troll alarms page
2.  Type in + click the token you want to search for
3.  See that the records presented don't change

**Expected behavior**
Only the matching records for the searched token should appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/76596635/169444175-05799e92-8d1f-4087-ac23-0e7eb16c54d4.png)

**Comment by hiemanshu** [comment]
@ajohn25 I am not able to reproduce this locally. Can you check if it's been fixed or still an issue?
