### ISSUE TITLE
Update Texter Conversation Button Configuration

### ISSUE THREAD

**Issue by kohlee** [politics-rewired/Spoke#1317]
**Is your feature request related to a problem? Please describe.**
See #840  

**Describe the solution you'd like**
In order that button appears:
- [ ]  Send button (unchanged)
- [ ] Canned responses button: Light blue instead of grey
- [ ] Opt out button (unchanged)
- [ ] Manage tags button (unchanged)
- [ ] Skip reply button: Change copy to 'Close'; White instead of grey
- [ ] Conversation number of numbers (unchanged)
- [ ] Previous / Next arrows: Change copy to '< PREV' and 'NEXT >' respectfully; turn into white-background buttons with no margins / space between the two

**Describe alternatives you've considered**
See [design doc](https://docs.google.com/drawings/d/1LDU0EB3JNtYIZRGTB5YtiwokfEZqkOr7f4_qMMAJq4I/edit)

**Additional context**
<img width="1024" alt="Screen Shot 2022-07-08 at 12 20 07 PM" src="https://user-images.githubusercontent.com/66085180/178057033-54b19e58-c20d-486e-b88e-69a70902a276.png">

MOBILE IMPLICATIONS:

- [ ] Change copy of 'Skip Reply' to read 'Close'; no need to change color - keep grey
- [ ] If possible, make PREVIOUS and NEXT buttons mirror desktop ('< PREV' and 'NEXT >' )

**Comment by ajohn25** [comment]
@hiemanshu we feel ready to hand this off! Let us know if you have questions

**Comment by hiemanshu** [comment]
> @hiemanshu we feel ready to hand this off! Let us know if you have questions

Sounds good! I’ll let you know if I need anything!

**Comment by kohlee** [comment]
@hiemanshu The button can stay "Reopen" like it currently reads! But this reminds me that we'll want to rename the button on the ToDos page to read "Closed Conversations" instead of "Skipped Conversations"
