### ISSUE TITLE
Campaign variables should populate in Interactions tab and Script Preview

### ISSUE THREAD

**Issue by kohlee** [politics-rewired/Spoke#1356]
**Is your feature request related to a problem? Please describe.**
To proof a campaign with campaign variables, users need to open two windows and cross reference the Campaign Variables section with the copy in the Interactions tab. This is time consuming and prone to errors.

**Describe the solution you'd like**
From Interactions, campaign variables should remain blue but populate with the values present in the Campaign Variables section. Once an interaction step is clicked into, the variables should show as their name rather than populated value.

From Script Preview, campaign variables should always populate with values rather than the variable name.

**Describe alternatives you've considered**
Campaign variables could fetch for Script Preview but not Interactions tab.

**Additional context**
Populate variables:
<img width="1024" alt="Screen Shot 2022-08-19 at 1 36 54 PM" src="https://user-images.githubusercontent.com/66085180/185703320-ecf39996-ca64-4bf6-91ec-41b709528297.png">
Don't populate variables:
<img width="1070" alt="Screen Shot 2022-08-19 at 1 37 10 PM" src="https://user-images.githubusercontent.com/66085180/185703354-19a04542-1fc1-4010-b3d8-ded7814a304a.png">

**Comment by hiemanshu** [comment]
@politics-rewired/organizing What happens here in case of invalid variables? CV / Otherwise? i.e. a campaign variable, but without a value, they are colored orange and left as is?

**Comment by ninabaldwin** [comment]
@hiemanshu yes, that's perfect
