### ISSUE TITLE
Opt out page should always have Export Opt Outs unfurled

### ISSUE THREAD

**Issue by ninabaldwin** [politics-rewired/Spoke#1457]
**Describe the bug**
The first time you access the Opt Outs page, it has the Export Opt Outs section unfurled so that you can see the buttons. However, after using the page and doing some imports, it collapses the section so that you no longer see the buttons. Even if I leave the instance altogether and come back, it is still collapsed and you cannot see the buttons unless you know how to unfurl.

**To Reproduce**

1.  Go to Opt Outs
2.  Import a number
3.  See that the buttons are no longer visible
4.  Go out of the page and come back and the buttons still aren't visible

**Expected behavior**
The Export Opt Outs should at least by default be unfurled every time you come back to the page. However, best case scenario I would think we should just never have it collapsed.

**Comment by bengilvar** [comment]
This is fixed - QAer!
