### ISSUE TITLE
After applying a tag, save and move on with out a message comes back to the queue

### ISSUE THREAD

**Issue by bengilvar** [politics-rewired/Spoke#1534]
- [ Y] I have searched through existing issues and did not find an existing report
Submitted by a user via helpscout! 

**Describe the bug**
Problem: When our users (texting volunteers on Spoke) apply a tag and then click
"SAVE AND MOVE ON WITHOUT A MESSAGE", Spoke moves user onto the next
message. User does not have chance to hit “CLOSE”. The tagged message is moved
back into "Send Replies" pile.
Here is an example:

![bug](https://user-images.githubusercontent.com/102557290/202478196-468d5c14-15d0-4dbb-80a9-bcbadb01738c.png)

Expected Action: When you tag the message and hit "SAVE AND MOVE ON
WITHOUT A MESSAGE", you could then hit “CLOSE” and the message would come
out of Send Replies list. After that, no user would see it again.

What is actually happening: When people tag a message and then hit “SAVE AND
MOVE ON WITHOUT A MESSAGE”, the user is being moved onto the next message
(without the opportunity to hit “CLOSE”) and the previously tagged message is going
back into the Send Replies list.

How That’s Impacting Things: Users are dealing with the same message multiple times.
Messages that have already been tagged are coming back to different users. (i.e. User
gets a new batch of replies, it looks like the message hasn’t been read until the user
goes to apply a tag and sees that the message has already been tagged by a previous
user). In short: volunteers are doing the same work twice & time is wasted.

Our Temporary Workaround: To tag a message and close it out of the replies list, we
read the message, apply a tag, click "SAVE AND TYPE A MESSAGE", then manually
clear out the message, then hit CLOSE. This is the only way we can get it out of the
replies list.

Conclusion: Please fix Spoke so that when you hit “SAVE AND MOVE ON WITHOUT A
MESSAGE”, it takes it out of your replies. Thank you!

**Comment by bengilvar** [comment]
@ajohn25 the submitted name dropped you as a friend from the Bernie campaign!

**Comment by ajohn25** [comment]
Closing issue - our recommendation was to use survey responses over tags in this case https://secure.helpscout.net/conversation/2070474120/7956/
