### ISSUE TITLE
Confirm that replies count on individual campaign details page reflects total inbounds

### ISSUE THREAD

**Issue by kohlee** [politics-rewired/Spoke#1548]
**Describe the bug**
The count under Replies on the individual campaign details page does not appear to reflect the total number of inbound messages. Users report confusion around whether the count includes opted out contacts or outbound replies sent by their texters. Various settings in Message Review do not result in a matching count.
 
**To Reproduce**

1. Go to a campaign details page (e.g. x.spokerewired.com/admin/1/campaigns/1)
2. Identify Replies count on top reporting panel 
3. Go to Message Review and filter for message status Needs Response and campaign ID 1; see differing count
4. Filter for Needs Response and Active Conversation and campaign ID 1; see differing count
5. Filter for Needs Response, Active Conversation, and Closed and campaign 1; see differing count
6. Repeat steps 3-4 while toggling Opt Outs on; see differing count on each

**Expected behavior**
Replies count should reflect the number of inbound messages received. 
As part of a future issue, a Needs Response count which excludes Opt Outs and reflects all Needs Response messages could also appear on the details page reporting panel.

**Comment by ajohn25** [comment]
@kohlee / @kohlkenn the replies count appears to be doing what's expected in the expected behavior section
https://github.com/politics-rewired/Spoke/blob/main/src/server/api/campaign.js#L180-L182

I think it's expected that Message Review won't easily show the same number because Message Review metrics are at the campaign contact / conversation level vs. the message level. Lmk if you want to close / modify this issue based on that info!

**Comment by kohlkenn** [comment]
This came from reports that the replies count on the campaign details page seemed to be (message count) - (count of initial messages sent). 

_Contact 1: Initial message sent
Contact 2: Initial message sent, contact replied, texter replied
Contact 3: Initial message sent, contact replied, texter replied, contact replied_

For the above case, the suspected behavior was that the campaign details page would list 5: count of all messages EXCEPT initial messages.

The desired behavior was that the campaign details page would list 2: a count of inbound replies only.

If we think the desired behavior is the actual behavior, all good here! The details about message review were to help explain the process admins undergo when investigating, but they kind of muddied the water here: You're right that the message review counts per message status aren't expected to match that replies count!

If we think the desired behavior is not the actual behavior, I could modify this issue with just the above info?

**Comment by ajohn25** [comment]
Yup just did a [spot check](https://metabase.rewired.dev/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgY291bnQoKikgZnJvbSBtZXNzYWdlIG0gXG5qb2luIGNhbXBhaWduX2NvbnRhY3QgY2Mgb24gbS5jYW1wYWlnbl9jb250YWN0X2lkID0gY2MuaWQgXG53aGVyZSBjYW1wYWlnbl9pZCA9IDI3NjYgYW5kIGlzX2Zyb21fY29udGFjdCIsInRlbXBsYXRlLXRhZ3MiOnt9fSwiZGF0YWJhc2UiOjEwMjV9LCJkaXNwbGF5Ijoic2NhbGFyIiwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==) and desired behavior seems to be in effect!
