### ISSUE TITLE
Order of survey questions - out of order 

### ISSUE THREAD

**Issue by elemm** [politics-rewired/Spoke#690]
- [x] I have searched through existing issues and did not find an existing report

**Describe the bug**
When you click on a campaign from the admin mode, the survey questions are out of order and so it is confusing.

**To Reproduce**
1. Go to a Campaign
2. scroll down to survey questions 
3. You will notice that the survey questions are not in the order that they are asked in the text script 

**Expected behavior**
Ideally it would be nice if these questions were in order, because it's hard to find the answer to the primary question in the summary format if they are out of order, and to understand.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser: Chrome

**Additional context**

**Comment by lh00000000** [comment]
(closing because I think it's the same as https://github.com/politics-rewired/Spoke/issues/496 and hopefully fixed-ish now with https://github.com/politics-rewired/Spoke/pull/809 )
