### ISSUE TITLE
Issues with dev set up: Auth0

### ISSUE THREAD

**Issue by hblumberg** [politics-rewired/Spoke#717]
- [x] I have searched through existing issues and did not find an existing report

**Describe the bug**
After completing the "Getting started" steps 1-12, clicking "Login and get started" leads to an Auth0 error page that reads "Looks like something went wrong!" (see screenshots).

**To Reproduce**
1. Complete steps 1-12 of ["Getting started."](https://github.com/politics-rewired/Spoke#getting-started) (The only place I deviated from the instructions was to add values for additional environment variables. See the issue [here](https://github.com/politics-rewired/Spoke/issues/716).)
2. Click "Login and get started."

**Expected behavior**
I expect to be prompted to create an organization, per "Getting started" step 14.

**Screenshots**
<img width="729" alt="Screen Shot 2020-08-23 at 2 13 36 PM" src="https://user-images.githubusercontent.com/8495791/90985667-72d39c00-e54b-11ea-8042-021d34500d1d.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: Version 84.0.4147.135

**Additional context**
* I don't think this is due to a service outage. I've worked on this over the course of multiple days and Auth0 has been reporting "All Systems Operational."
* There is no record in https://manage.auth0.com/dashboard/us/USERNAME/logs to help debug.

Thanks in advance!

**Comment by ben-pr-p** [comment]
Hey @hblumberg , we have stopped using Auth0 and aren't too interested in maintaining it - are you interested in using it? I'd suggest using local login

**Comment by hblumberg** [comment]
I was just following the "Getting started" instructions -- I'm not attached to Auth0 at all (: Can you point me to any documentation on local login?

**Comment by ben-pr-p** [comment]
Yep, just set `PASSPORT_STRATEGY=local` in your `.env` and then you're all good to go

**Comment by hblumberg** [comment]
Great, thank you so much! Closing out this ticket.
