### ISSUE TITLE
Saving teams doesn't work properly

### ISSUE THREAD

**Issue by aradox66** [politics-rewired/Spoke#820]
**Your issue may already be reported!**
Please search on the [issue tracker](../) before creating one.

- [x] I have searched through existing issues and did not find an existing report

**Describe the bug**
Saving new teams to a campaign doesn't work unless 'restrict to teams' is selected. Currently, to get the function to work reliably, you have to add teams, restrict to those teams and save, then refresh, unrestrict and save again.

If you save the teams without restricting, the teams will disappear on refresh.

**Expected behavior**
The teams should save without needing to restrict the campaign to those teams.

**Desktop (please complete the following information):**
Chrome: Version 87.0.4280.109 (Official Build) (64-bit)
Mozilla Firefox 83.0

**Comment by ben-pr-p** [comment]
Thanks for the issue @aradox66 !

Adding to Q4 feature freeze as it meets the requirements and is reproducible.

**Comment by aradox66** [comment]
Amazing, thanks so much.
