### ISSUE TITLE
Display tailored message in texter todos for users with assignment status Do Not Assign

### ISSUE THREAD

**Issue by kohlee** [politics-rewired/Spoke#828]
**Is your feature request related to a problem? Please describe.**
For texters with assignment status Do Not Assign, the texter todos page currently displays "No texts available right now.
Watch out for an announcement when new texts are available!" rather than an indication that they have been placed on hold. 

**Describe the solution you'd like**
User reports a desire for the texter todos page to read something like, "Your ability to request texts has been put on hold. Please contact a text team leader" for texters placed on Do Not Assign. 

**Describe alternatives you've considered**
In programs I (Kohlee) have run, it was desirable for the page to read "No texts available right now.
Watch out for an announcement when new texts are available!" for cases when texts were out _and_ when a texter was placed on Do Not Assign. This allowed time for a team leader to contact the texter in Slack, explain that they were now disallowed from requesting texts and share options for remedying the situation. This was under the assumption that displaying a message indicating that they were being punished or prohibited from volunteering could result in unnecessary aggression or anxiety on behalf of the texter. 

The flow for curbing undesireable behaviors with a message like, "No texts available right now":

1. Texter sees "no texts available" message in Spoke
1. Texter looks for more information in Slack
1. Texter sees direct message from Sweeper describing the problem and offering solutions (sent at the moment the texter was placed on Do Not Assign)
1. Texter enters conversation with Sweeper, hopefully reacts privately, calmly and productively, and has their right to request texts reestablished

A possible flow for including a message like, "Your ability to request texts has been put on hold":

1. Texter sees warning message and feels sad/angry/anxious
1. Texter heads to a public texting channel in Slack and posts regarding their assignment request status
1. Sweeper tries to move conversation into a direct message to explain paths toward reestablishing their request abilities
1. Other texters join the heated thread in the public Slack channel and the texter doesn't receive or retain feedback

That second flow could go differently depending on the program; an alternative solution would be giving admins the choice to display a tailored message to Do Not Assign texters, and having that toggle and text box available in Settings.

**Comment by hiemanshu** [comment]
@kohlee @bchrobot I need 2 things for this, mainly copy:

1. In Settings what is the section called and what are the options. There will be 1 Header, and 2 options.
2. In the texter view, what is the common title called? We can set the text below the title which currently reads: " Watch out for an announcement when new texts are available! " to whatever is setup in the settings, but the title which reads: " No texts available right now ", will remain static. Or will this be an option too?

Settings Section, Required Copy:

Section Header -- "Do Not Approve Message"
Toggle -- "Show texters a different message if they are set to Do Not Approve"
Default text -- "Your status has been set to do not assign, contact a text team leader for help"

**Comment by bengilvar** [comment]
I'm trying to QA this. Is there an instance where the changes are merged that I should try to mark myself Do not Assign? Right now I just get the message: Give us a few minutes to assign your texts. You'll receive an email notification when we've done so. If you requested your texts after hours, you’ll get them when texting opens at 9am ET :)

Even when I'm set to Do not approve
