### ISSUE TITLE
Fix campaign filter in Bulk Script Editor 

### ISSUE THREAD

**Issue by kohlee** [politics-rewired/Spoke#841]
* [x] I have searched through existing issues and did not find an existing report

**Describe the bug**
When using the Bulk Script Editor with campaigns selected to narrow the focus of the edits, the request is not executed as expected. It is possible that scripts only reflect changes in Bulk Script Editor if no campaigns are selected as filters.

**To Reproduce**

1.  Go to Bulk Script Editor
1.  Select a set of campaigns to narrow the scope of the edits
1.  Indicate content that should be replaced and execute request
1.  Check campaigns selected in step 2 and fail to see the expected changes.

**Expected behavior**

1.  Go to Bulk Script Editor
1.  Select a set of campaigns to narrow the scope of the edits
1.  Indicate content that should be replaced and execute request
1.  Changes are reflected in the campaigns from step 2 but no other campaigns.

**Desktop (please complete the following information):**

* OS: iOS
* Browser: Chrome, Safari
* Version 10.15.7

**Comment by hiemanshu** [comment]
@politics-rewired/organizing I am unable to reproduce this on the latest version. If someone can reproduce this, can you help me with a video so I can see what's happening? Thanks!

**Comment by kohlee** [comment]
https://user-images.githubusercontent.com/66085180/178047075-76650c0f-bf23-4898-9496-05ee9abef351.mov

@hiemanshu Let me know if this makes sense/is possible and I can write it out in terms of what we're ultimately looking for!

**Comment by hiemanshu** [comment]
Sounds good @kohlee. I'm going to write it out, and you can flesh it out as needed.

1. Change the Filter Campaigns to be more like Contact Overlap, it's an auto complete field that you can then use to pick the campaigns you want to limit this to. If it's empty, just replace it everywhere.
2. Show a confirmation dialog, with the list of campaigns it will change, and what the updated text will look like, with changes being marked in a color (Orange? Green?), and then when the user confirms that, it then makes the changes, and shows the report like it does right now. 

Let me know if I missed anything!

**Comment by hiemanshu** [comment]
And as requested going to tag @politics-rewired/organizing and not just kohlee :)

**Comment by ninabaldwin** [comment]
@hiemanshu yes this looks good! We would like the color to be orange! Thank you!!!

**Comment by hiemanshu** [comment]
@politics-rewired/organizing @bchrobot thoughts on this:

<img width="1930" alt="Screenshot 2022-07-26 at 1 54 33 PM" src="https://user-images.githubusercontent.com/367605/180959918-3866236a-22c7-4ba6-97e7-98070fda4f4f.png">

**Comment by hiemanshu** [comment]
<img width="1715" alt="Screenshot 2022-07-27 at 6 20 25 PM" src="https://user-images.githubusercontent.com/367605/181251309-8ae23c4e-a2f2-4903-bd86-987e52699f7e.png">
<img width="1709" alt="Screenshot 2022-07-27 at 6 20 51 PM" src="https://user-images.githubusercontent.com/367605/181251328-55892a48-cf45-4306-b349-7a5ce09891dd.png">
