### ISSUE TITLE
Tags Unable to be Selected on iPad

### ISSUE THREAD

**Issue by michaelratliff** [politics-rewired/Spoke#892]
**Your issue may already be reported!**
Please search on the [issue tracker](../) before creating one.

- [X] I have searched through existing issues and did not find an existing report

**Describe the bug**
When using an iPad and attempting to select tags from the Manage Tags interface, user is unable to select the tag and select the Save button.

**To Reproduce**
Apply tags on iPad

**Expected behavior**
Selecting tags does not prevent user from selecting Save.

**Screenshots**

**Smartphone (please complete the following information):**

- Device: iPad
- OS: iOS
- Browser Safari

**Comment by kohlee** [comment]
Hey @michaelratliff! Is this resolved, or should I reopen?
