### ISSUE TITLE
Clarify canned responses instructional copy

### ISSUE THREAD

**Issue by kohlee** [politics-rewired/Spoke#984]
**Is your feature request related to a problem? Please describe.**
Canned responses are sometimes mistakenly used in place of survey responses, rather than as supplementary FAQ responses.

**Describe the solution you'd like**
Instructional copy within the canned responses section of the campaign builder should read:

> Canned responses for texters
> Share additional FAQ responses with your texters that are NOT associated with logging data. Please note that canned responses are not tracked or stored when used. Responses associated with data collection should be included in your [interaction script](https://docs.spokerewired.com/article/43-create-interaction-script) instead.

rather than 

> Canned responses for texters
> Save some scripts for your texters to use to answer additional FAQs that may come up outside of the survey questions and scripts you already set up.

**Describe alternatives you've considered**
Users could receive a warning message upon starting a campaign if a question response has not been created on that campaign. The warning message could link to documentation about survey responses versus question responses.

**Comment by ajohn25** [comment]
@politics-rewired/spoke-client Using this as an opportunity to test new processes! Items to review:
1. 👍🏾 on copy?
2. Should we create a follow up issue for the alternative described?

**Comment by ninabaldwin** [comment]
@ajohn25 @jstgriswold is going to add a hyperlink to the copy and @kohlee is going to create a github issue for the alternative.
